[package]
name = "slugify-rs"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deunicode = "1.3.1"
nanoid = "0.4.0"
